site_name: CannonKeys Documentation
theme:
  name: 'material'
  logo: 'images/white_transparent_256.png'
  favicon: 'images/logo.png'
repo_name: 'cannonkeys/ck-docs'
repo_url: 'https://github.com/cannonkeys/ck-docs'
markdown_extensions:
  - admonition
nav:
  - Home: index.md
  - Build Guide: bluepill-build.md
  - Adding RGB Underglow: rgb_underglow.md
  - Using Low Profile Sockets: sockets.md
  - Flashing Guide: flashing.md
  - Firmware Guide: firmware.md
  - Bluepill Modification: bluepill-mod.md
  - Testing your Bluepill: bluepill-test.md
  - Default layouts: default-layouts.md

extra:
  social:
    - type: 'github'
      link: 'https://github.com/cannonkeys'
    - type: 'instagram'
      link: 'https://www.instagram.com/cannon.keys/'
